// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportShop.Data;

#nullable disable

namespace SportShop.Migrations
{
    [DbContext(typeof(SportShopDbContext))]
    partial class SportShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SportShop.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderPlaced")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OrderTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("SportShop.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("SportShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTrendingProduct")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Gym",
                            Detail = "Tạ đúc nguyên khối bọc cao su cao cấp chống trầy xước sàn",
                            ImageUrl = "/assets/images/ta-tay.jpg",
                            IsTrendingProduct = true,
                            Name = "Tạ Tay Cao Su 5kg",
                            Price = 150m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Gym",
                            Detail = "Ghế dốc tập cơ bụng, cơ ngực có thể gấp gọn tiện lợi",
                            ImageUrl = "/assets/images/ghe-tap.jpg",
                            IsTrendingProduct = true,
                            Name = "Ghế Tập Bụng Đa Năng",
                            Price = 1250m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Gym",
                            Detail = "Hỗ trợ tập cơ bụng sáu múi hiệu quả tại nhà kèm thảm lót gối",
                            ImageUrl = "/assets/images/con-lan.jpg",
                            IsTrendingProduct = false,
                            Name = "Con Lăn Bụng 3 Bánh",
                            Price = 120m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Gym",
                            Detail = "Bộ 5 dây lực kéo khác nhau hỗ trợ tập tạ và căng cơ toàn thân",
                            ImageUrl = "/assets/images/day-ngu-sac.jpg",
                            IsTrendingProduct = false,
                            Name = "Dây Ngũ Sắc Kháng Lực",
                            Price = 180m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Yoga",
                            Detail = "Thảm chất liệu TPE 6mm thân thiện môi trường, chống trượt tuyệt đối",
                            ImageUrl = "/assets/images/tham-yoga.jpg",
                            IsTrendingProduct = true,
                            Name = "Thảm Yoga Định Tuyến",
                            Price = 350m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Yoga",
                            Detail = "Khung nhựa ABS chịu lực 150kg mở vai uốn lưng chuyên sâu",
                            ImageUrl = "/assets/images/vong-yoga.jpg",
                            IsTrendingProduct = false,
                            Name = "Vòng Tập Yoga Chịu Lực",
                            Price = 280m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Yoga",
                            Detail = "Bóng dầy dặn chống nổ giữ form tốt tặng kèm bơm tay siêu tốc",
                            ImageUrl = "/assets/images/bong-yoga.jpg",
                            IsTrendingProduct = false,
                            Name = "Bóng Yoga PVC Trơn 65cm",
                            Price = 160m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Yoga",
                            Detail = "Khối xốp EVA mật độ cao hỗ trợ giữ thăng bằng các tư thế khó",
                            ImageUrl = "/assets/images/gach-yoga.jpg",
                            IsTrendingProduct = false,
                            Name = "Gạch Xốp Hỗ Trợ Yoga",
                            Price = 60m
                        },
                        new
                        {
                            Id = 9,
                            Category = "Chạy bộ",
                            Detail = "Đế cao su giảm chấn đàn hồi tốt, vải mesh thoáng khí cho runner",
                            ImageUrl = "/assets/images/giay-chay.jpg",
                            IsTrendingProduct = true,
                            Name = "Giày Chạy Siêu Nhẹ Air",
                            Price = 850m
                        },
                        new
                        {
                            Id = 10,
                            Category = "Chạy bộ",
                            Detail = "Chất liệu co giãn chống nước tốt có ngăn chứa chìa khóa xe",
                            ImageUrl = "/assets/images/dai-chay.jpg",
                            IsTrendingProduct = false,
                            Name = "Đai Đeo Điện Thoại Runner",
                            Price = 75m
                        },
                        new
                        {
                            Id = 11,
                            Category = "Chạy bộ",
                            Detail = "Nhựa Tritan an toàn không BPA, có vạch chia dung tích tiện lợi",
                            ImageUrl = "/assets/images/binh-nuoc.jpg",
                            IsTrendingProduct = false,
                            Name = "Bình Nước Thể Thao 1L",
                            Price = 95m
                        },
                        new
                        {
                            Id = 12,
                            Category = "Chạy bộ",
                            Detail = "Chất cotton dày dặn thấm hút mồ hôi chống phồng rộp gót chân",
                            ImageUrl = "/assets/images/tat-chay.jpg",
                            IsTrendingProduct = false,
                            Name = "Tất Thể Thao Cổ Ngắn (3 Đôi)",
                            Price = 50m
                        },
                        new
                        {
                            Id = 13,
                            Category = "Bóng đá",
                            Detail = "Đạt tiêu chuẩn thi đấu quốc tế, chất da PU bền bỉ đường may kín",
                            ImageUrl = "/assets/images/bong-da.jpg",
                            IsTrendingProduct = true,
                            Name = "Bóng Đá Thi Đấu Số 5",
                            Price = 450m
                        },
                        new
                        {
                            Id = 14,
                            Category = "Bóng đá",
                            Detail = "Lòng găng latex bám dính tốt có xương bảo vệ chống lật ngón tay",
                            ImageUrl = "/assets/images/gang-tay.jpg",
                            IsTrendingProduct = false,
                            Name = "Găng Tay Thủ Môn Có Xương",
                            Price = 320m
                        },
                        new
                        {
                            Id = 15,
                            Category = "Bóng đá",
                            Detail = "Nhựa PP chịu lực lót mút EVA êm ái bảo vệ chân giảm va chạm",
                            ImageUrl = "/assets/images/boc-ong-dong.jpg",
                            IsTrendingProduct = false,
                            Name = "Băng Bảo Vệ Ống Quyển",
                            Price = 45m
                        },
                        new
                        {
                            Id = 16,
                            Category = "Bóng đá",
                            Detail = "Hỗ trợ cố định khớp gối, dây đai tăng cường giảm áp lực dây chằng",
                            ImageUrl = "/assets/images/bang-goi.jpg",
                            IsTrendingProduct = false,
                            Name = "Băng Gối Thể Thao Bản Rộng",
                            Price = 110m
                        },
                        new
                        {
                            Id = 17,
                            Category = "Cầu lông",
                            Detail = "Khung carbon nguyên khối siêu nhẹ lực căng tốt trợ lực cho cổ tay",
                            ImageUrl = "/assets/images/vot-cau.jpg",
                            IsTrendingProduct = true,
                            Name = "Vợt Cầu Lông Khung Carbon",
                            Price = 680m
                        },
                        new
                        {
                            Id = 18,
                            Category = "Cầu lông",
                            Detail = "Cầu Thành Công độ bền lông cầu cao đường bay đầm quỹ đạo chuẩn ổn định",
                            ImageUrl = "/assets/images/hop-cau.jpg",
                            IsTrendingProduct = false,
                            Name = "Hộp Cầu Lông 12 Quả",
                            Price = 190m
                        },
                        new
                        {
                            Id = 19,
                            Category = "Cầu lông",
                            Detail = "Vải chống thấm nước dày dặn đựng vừa 3 cây vợt và giày quần áo",
                            ImageUrl = "/assets/images/bao-vot.jpg",
                            IsTrendingProduct = false,
                            Name = "Bao Vợt Cầu Lông 2 Ngăn",
                            Price = 150m
                        },
                        new
                        {
                            Id = 20,
                            Category = "Cầu lông",
                            Detail = "Chất liệu cao su non siêu bám tay thấm hút mồ hôi chống trơn trượt",
                            ImageUrl = "/assets/images/quan-can.jpg",
                            IsTrendingProduct = false,
                            Name = "Cuộn Quấn Cán Vợt (Combo 5 chiếc)",
                            Price = 35m
                        });
                });

            modelBuilder.Entity("SportShop.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingCartId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SportShop.Models.OrderDetail", b =>
                {
                    b.HasOne("SportShop.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportShop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SportShop.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("SportShop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SportShop.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
